### ISSUE TITLE
Configure default branch

### ISSUE THREAD

**Issue by nathonius** [elstgav/branch-manager#4]
Obviously I can just go into the plugin and customize my version of it, but it would be neat to be able to override the default branch (master, currently) with a different one. As an example, for my personal projects i tend to use `main` these days, but at work we use `development`.

**Comment by elstgav** [comment]
Great point! Admittedly, I ran into this recently as well (and changed locally). Looks like it should be [fairly simple to infer the default branch name](https://stackoverflow.com/a/55448881/625710) too.
